### ISSUE TITLE
Feature request: call-site usage of PublicAPI.@strict

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaExperiments/PublicAPI.jl#1]
Consider the following example:

```julia
import PublicAPI

function foo(x, y, z)
    a = PublicAPI.@strict Upstream.api(x, y, z)
    ...
end
```

If `Upstream.api` has been declared public in the `Upstream.jl` package, then `a = PublicAPI.@strict Upstream.api(x, y, z)` would just turn into `a = Upstream.api(x, y, z)`.

However, if `Upstream.api` has NOT been declared public, then `a = PublicAPI.@strict Upstream.api(x, y, z)` would throw an error.

**Comment by tkf** [comment]
I was actually thinking lowering

```julia
PublicAPI.@strict import Module
```

to

```julia
baremodule $Dummy
import Module as $tmp
for api in $PublicAPI.of($tmp)
    n = nameof(api)
    @eval const $n = $(Module(api)).$n
end
end
const Module = $Dummy
```

so that `Module.f` works only if `f` is public. I think this is easy to use since you don't need to pepper `@strict` everywhere. It's also easy to ditch PublicAPI.jl dependency.

**Comment by DilumAluthge** [comment]
> so that Module.f works only if f is public

This is really nice!

**Comment by DilumAluthge** [comment]
Could we have some kind of "fall-back" for the rare cases in which you actually want to use internal functions? It could be verbose, e.g. something like this:

```julia
import PublicAPI

PublicAPI.@strict import Upstream

function foo(x, y, z)
    a = Upstream.api(x, y, z)
    ...
end

function bar(x, y, z)
    b = PublicAPI.@allow_internal Upstream.some_private_thing(x, y, z)
    ...
end
```

I  think that for most people, most of the time they will be using only the public API of `Upstream`. But I do think that occasionally people will want to use one or two internal functions.

**Comment by tkf** [comment]
We ignore (or rather can't interfere with) "bare" `using`/`import` so you can always use it to touch internals. Maybe a good idiom is

```julia
PublicAPI.@strict import Upstream
import Upstream as UpstreamInternal
UpstreamInternal.some_private_thing(x, y, z)
```

?
